### ISSUE TITLE
Improve UX of the Contribution List 

### ISSUE THREAD

**Issue by seiya1223** [Microsoft/mvp#83]
1. It is better just use one progress ring. And user should not see the grid while initializing(iOS).
![image](https://user-images.githubusercontent.com/8097597/32882303-df1d7d60-caee-11e7-8064-1db0649767e4.png)
2. We should just load 10-20 contributions while initializing and load more when push to refresh. And for current version, if we just load 20 contributions we will see white space on the top.
![image](https://user-images.githubusercontent.com/8097597/32882306-e2ed2242-caee-11e7-90a2-f520c85f833e.png)

**Comment by jfversluis** [comment]
Was just about to open an issue on this. IMHO there is no need to show a blocking loading indicator and also the list scrolls to the top, while I'm scrolling to the bottom which loads new items. This causes that I have to scroll all the way from the top with each new batch that is loaded.

**Comment by jamesmontemagno** [comment]
The top one is just fro the pull to refresh. Probably could optimize on it, but isn't terrible.

**Comment by jamesmontemagno** [comment]
It shouldn't scroll to the top though, i haven't experienced that at all.

**Comment by jfversluis** [comment]
I've recorded scrolling to the top for you; https://youtu.be/Clp9SXS5Ycs

**Comment by jamesmontemagno** [comment]
Weird it doesn't do it on Android

**Comment by Depechie** [comment]
Can confirm the scroll to top behaviour on iOS too

**Comment by Depechie** [comment]
@jamesmontemagno the scroll to top is caused by the fact that the IsBusy property in the MyProfileViewModel class file is set to true when loading more items.
This triggers showing the spinner of the listview as though you did a pull to refresh. So somehow the code from Xamarin for that listview spinner also triggers a goto top!

Seeing the remarks in this issue, I'll fix the issue by no longer setting the IsBusy to true for the LoadMoreItems command... the full page loading popup will still be shown!
